development:
  adapter: postgresql
  encoding: utf8
  database: fluential_development
  pool: 5
  username: johnfigueiredo
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: fluential_test
  pool: 5
  username: johnfigueiredo
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: fluential_production
  pool: 5
  username: johnfigueiredo
  password:
