# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bffc5d3d6dc416a66a3adc51eee240e16e17c76a8b125216128cc2fcf23a2e0cacbd0cab69c8f49b4fca48e6e7b6a13cac6c2d10facb5936ea709b2856dcaf3

test:
  secret_key_base: 7adfc5a95a28375c23d2c7dc1df9cba6544b315236e82ee7257f0352444edbd38b7e8c046190a3a65a8cfbe8db175836b06563e6100daf59d02e5a16aecd4cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
